/** @format */

import type { Metadata } from "next";
import style from "../../style/global.module.css";
import "bootstrap/dist/css/bootstrap.min.css";
import "../../style/Customization.css";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <head>
        <link
          href='https://fonts.googleapis.com/css2?family=Recoleta:wght@400;500;700;800;900&display=swap'
          rel='stylesheet'
        />
      </head>
      <body className={style.body}>{children}</body>
    </html>
  );
}
